apiVersion: v1
kind: PersistentVolume
metadata:
  name: altinn-storage-repo-premium-volume
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: altinnstoragerepo
    readOnly: false
  claimRef:
    name: altinn-storage-repo-premium-volume-claim
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: altinn-storage-repo-premium-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
